// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RadiantCourseRegistration.Data;

#nullable disable

namespace RadiantCourseRegistration.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250206172814_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RadiantCourseRegistration.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Instructor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 201,
                            CreatedBy = "Admin",
                            CreatedOn = new DateTime(2025, 2, 6, 20, 28, 14, 108, DateTimeKind.Local).AddTicks(4671),
                            Description = "Learn the fundamentals of ASP.NET Core.",
                            Duration = "6 Weeks",
                            Instructor = "Anwar Bilcha",
                            Title = "ASP.NET Core Basics",
                            UpdatedBy = "",
                            UpdatedOn = new DateTime(2025, 2, 6, 20, 28, 14, 109, DateTimeKind.Local).AddTicks(1094)
                        },
                        new
                        {
                            Id = 302,
                            CreatedBy = "Admin",
                            CreatedOn = new DateTime(2025, 2, 6, 20, 28, 14, 109, DateTimeKind.Local).AddTicks(1435),
                            Description = "Master EF Core for data access.",
                            Duration = "4 Weeks",
                            Instructor = "Birhan Nega Smith",
                            Title = "Entity Framework Core",
                            UpdatedBy = "",
                            UpdatedOn = new DateTime(2025, 2, 6, 20, 28, 14, 109, DateTimeKind.Local).AddTicks(1437)
                        },
                        new
                        {
                            Id = 403,
                            CreatedBy = "Admin",
                            CreatedOn = new DateTime(2025, 2, 6, 20, 28, 14, 109, DateTimeKind.Local).AddTicks(1439),
                            Description = "Build interactive web apps with Blazor.",
                            Duration = "8 Weeks",
                            Instructor = "Kibru G.",
                            Title = "Blazor Web Development",
                            UpdatedBy = "",
                            UpdatedOn = new DateTime(2025, 2, 6, 20, 28, 14, 109, DateTimeKind.Local).AddTicks(1440)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
